### ISSUE TITLE
Add image loading system

### ISSUE THREAD

**Issue by Vinetos** [C-Text/CText#3]
The program must read images.

# Behaviour

Images will be given in arguments.
```shell
./ctext -i image1.bmp image2.bmp image3.bmp
```

or

```shell
./ctext -i image1.bmp -d path/to/folder/with/images
```

# Todo-list
- [ ] Support bitmap (`.bmp`) format
- [ ] Support path of files and folders
- [ ] Print an error if the image is invalid (bad format, can't read, doesn't exist, etc.)
